### ISSUE TITLE
how to open admin page while running the app??

### ISSUE THREAD

**Issue by vatsal-26** [sanjaysans/FoodOrderingAppForCanteen-Cassia#10]

**Comment by sanjaysans** [comment]
need to setup a firebase console and add admin user directly in firebase.. Then you can login in same app

**Comment by vatsal-26** [comment]
> need to setup a firebase console and add admin user directly in firebase.. Then you can login in same app

i didn't get you??

**Comment by vatsal-26** [comment]
> > need to setup a firebase console and add admin user directly in firebase.. Then you can login in same app
> 
> i didn't get you??

can you please list down the steps to do that??
