### ISSUE TITLE
How to access admin panel

### ISSUE THREAD

**Issue by sahudevansh** [sanjaysans/FoodOrderingAppForCanteen-Cassia#8]
How can we access the admin panel?
Please provide the admin id and password.

**Comment by sanjaysans** [comment]
Need to setup a firebase console and add admin user directly in firebase.. Then you can login in same app

**Comment by vatsal-26** [comment]
> How can we access the admin panel?
> Please provide the admin id and password.

bro if you managed to do please tell me how to do it
